config/routes.rb
Symbio::Application.routes.draw do

  devise_for :users # user authentication

  match '/orders/toggle' # toggle orders (xhr)
  match '/bestellungen' => 'orders#index', :as => 'orders' 
  match '/rechnungen' => 'invoice_items#index', :as => 'invoice_items'
  match '/daily_order' => 'dashboard#daily_order'
  match '/preisliste' => 'pages#pricelist', :as => 'pricelist'

  namespace :admin do # admins only
    match 'orders/by_month', :as => :orders_by_month
    match 'users/top_up'
    resources :orders
    resources :invoice_items
    resources :menu_items do
      get :autocomplete_menu_item_name, :on => :collection
    end
    resources :meal_categories
    resources :users
  end
  
  root :to => 'dashboard#index' # front page
  match '*path' => 'dashboard#bad_route' # everything else
  
end

app/models/menu_item.rb
class MenuItem < ActiveRecord::Base
  
  has_many :orders
  belongs_to :meal_category
  
  validates_presence_of :date, :name, :meal_category_id, :sort_order, :price
  
  def orderable?
    (self.date.to_time_in_current_zone + 12.hours - Order.offset) > Time.current
  end
  
end

app/controllers/admin/menu_items_controller.rb
module Admin
  class MenuItemsController < BaseController

    set_tab :admin_menu_items

    def index
    end

    def create
      index = params[:menu_item].keys[0]

      if menu_item = MenuItem.where(:date => params[:menu_item][index][:date], :meal_category_id => params[:menu_item][index][:meal_category_id]).first
        if params[:name] == "" then params[:name] = "-" end
        menu_item.name = params[:name]
      else
        menu_item = MenuItem.new
        menu_item.date = params[:menu_item][index][:date]
        menu_item.name = params[:name]
        menu_item.meal_category_id = params[:menu_item][index][:meal_category_id]
        menu_item.sort_order = menu_item.meal_category.sort_order
        menu_item.price = menu_item.meal_category.price
      end

      menu_item.save!
      
      @return = {
        :status => "ok",
        :name => params[:name],
      }

      respond_to do |format|
        format.html { render :nothing => true }
        format.json { render :json => @return }
      end
    end

    # Override for autocomplete :menu_item, :name
    def autocomplete_menu_item_name
      menu_items = MenuItem.select('DISTINCT name').where('name LIKE ?', params[:term] + '%').order(:name)
      render :json => menu_items.collect {|item| {"id" => item.id, "label" => item.name, "value" => item.name}}
    end

  end
end

app/views/admin/menu_items/_menu_items_for_week.erb
<%
# Load all existing menu items
menu_items_array = MenuItem.where(:date => date).order("date, sort_order")
current_menu_item = menu_items_array.shift 

# Iterate through all days in the given date range
date.each do |day| %>

	<% if day.today? then menu_class = :box end %>

	<%= content_tag :div, :class => menu_class do %>
	
	<h3><%= l(day, :format => :complete) %></h3>

	<ul>
	<% MealCategory.order(:sort_order).each do |meal_category| %>

		<%= form_for MenuItem.new, :url => {:action => :create, :format => :json}, :remote => true do |f| %>

			<li class="editable_menu_item">
			<%= f.label meal_category.name %>:

			<% if !current_menu_item.nil? && current_menu_item.date == day && current_menu_item.meal_category_id.to_i == meal_category.id.to_i %>
				<span class="click_to_edit" title="Click to edit!"><%= current_menu_item.name %></span>
				<%= text_field_tag :name, current_menu_item.name, :style => 'display: none;', :autocomplete => autocomplete_menu_item_name_admin_menu_items_path %>
				<input name="menu_item[<%= day.to_time.to_i.to_s + meal_category.id.to_s %>][id]" type="hidden" value="<%= current_menu_item.id %>" />
				<% current_menu_item = menu_items_array.shift %>
			<% else %>
				<span class="click_to_edit" title="Click to edit!"></span>
				<%= text_field_tag :name, '', :autocomplete => autocomplete_menu_item_name_admin_menu_items_path %>
			<% end %>

			<input name="menu_item[<%= day.to_time.to_i.to_s + meal_category.id.to_s %>][meal_category_id]" type="hidden" value="<%= meal_category.id.to_s %>" />
			<input name="menu_item[<%= day.to_time.to_i.to_s + meal_category.id.to_s %>][date]" type="hidden" value="<%= day %>" />
			</li>

		<% end %>

	<% end # /each %>
	</ul>

	<% end # /content_tag %>
<% end # /each %>

app/views/admin/menu_items/index.html.erb
<div id="current_week" class="span-12 border">
    <div class="span-11 append-1 last">

        <h2>Menü für diese Woche</h2>

		<%= render :partial => 'menu_items_for_week', :locals => { :date => Time.current.to_date.beginning_of_week..(Time.current.to_date.end_of_week - 2.days) } %>

    </div>
</div>

<div id="next_week" class="span-11 prepend-1 last">
    <h2>Menü für nächste Woche</h2>

		<%= render :partial => 'menu_items_for_week', :locals => { :date => Time.current.to_date.next_week..(Time.current.to_date.next_week + 4.days) } %>

</div>