config/routes.rb
Symbio::Application.routes.draw do

  devise_for :users # user authentication

  match '/orders/toggle' # toggle orders (xhr)
  match '/bestellungen' => 'orders#index', :as => 'orders' 
  match '/rechnungen' => 'invoice_items#index', :as => 'invoice_items'
  match '/daily_order' => 'dashboard#daily_order'
  match '/preisliste' => 'pages#pricelist', :as => 'pricelist'

  namespace :admin do # admins only
    match 'orders/by_month', :as => :orders_by_month
    match 'users/top_up'
    resources :orders
    resources :invoice_items
    resources :menu_items do
      get :autocomplete_menu_item_name, :on => :collection
    end
    resources :meal_categories
    resources :users
  end
  
  root :to => 'dashboard#index' # front page
  match '*path' => 'dashboard#bad_route' # everything else
  
end

app/views/layouts/application.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
    <head>
        <meta http-equiv="content-type" content="text/html;charset=UTF-8" />
        <title>symbio | eat beta together</title>

        <link rel="stylesheet" href="/stylesheets/blueprint/screen.css" type="text/css" media="screen, print"/>
        <link rel="stylesheet" href="/stylesheets/print.css" type="text/css" media="print"/>
        <%= stylesheet_link_tag 'symbio' %>
		<%= stylesheet_link_tag 'smoothness/jquery-ui-1.8.7.custom.css' %>
        
        <%= javascript_include_tag :defaults %>
    </head>
    <body>
        <div class="container _showgrid">
            <div class="span-5 prepend-top">
                <h1><a href="/" style="color: #000;">symbio</a></h1>
            </div>
            <div class="span-14 prepend-top">
                <% if !flash.empty? %>
                <% if flash[:error] %>
                <%= content_tag :div, flash[:error], :id => :flash, :class => :error %>
                <% elsif flash[:alert] %>
                <%= content_tag :div, flash[:alert], :id => :flash, :class => :alert %>
                <% elsif flash[:notice] %>
                <%= content_tag :div, flash[:notice], :id => :flash, :class => :notice %>
                <% elsif flash[:success] %>
                <%= content_tag :div, flash[:success], :id => :flash, :class => :success %>
                <% end %>
                <% else %>
                <div id="flash">
                </div>
                <% end %>
            </div>
            <div id="header" class="span-5 prepend-top last" style="text-align: right;">
                <% if user_signed_in? %>
                <div><%= current_user.name %></div>
                <%= link_to "Abmelden", destroy_user_session_path %>
                <% else %>
                <div>Noch keine Zugangsdaten?</div>
                <%= link_to "Jetzt registrieren!", new_user_registration_path %>
                <% end %>
            </div>
            <% if user_signed_in? && current_user.admin? %>
            <hr/>
            <div id="admin_menu" class="span-24 last" style="text-align: center;">
                <div class="menu box">
                    <%= tabs_tag do |tab| %>
                    <%= tab.admin_orders 'Bestellübersicht', admin_orders_path %>
                    <%= tab.admin_invoice_items 'Rechnungsübersicht', admin_invoice_items_path %>
                    <%= tab.admin_orders_by_month 'Monatsübersicht', admin_orders_by_month_path %>
                    <%= tab.admin_menu_items 'Menüeinträge', admin_menu_items_path %>
                    <%= tab.admin_meal_categories 'Speisekategorien', admin_meal_categories_path %>
                    <%= tab.admin_users 'Benutzer', admin_users_path %>
                    <% end %>
                </div>
            </div>
            <% if InvoiceItem.missing_invoices? %>
			<hr/>
            <div id="admin_notification" class="span-22 prepend-1 append-1 append-bottom last notice" style="text-align: center; border: none;">
                Es gibt neue Bestellungen! <span style="text-decoration: underline;"><%= link_to 'Jetzt bestätigen, Rechnungen erstellen und Bestell-E-Mail versenden!', "/daily_order" %></span>
            </div>
            <% end %>
            <% end %>
            <% if user_signed_in? %>
            <hr/>
			<div id="user_menu" class="span-20 prepend-2 append-2 append-bottom last menu" style="text-align: center;">
                <%= tabs_tag do |tab| %>
                <%= tab.dashboard 'Meine Bestellungen', root_path %>
                <%= tab.orders 'Bestellübersicht', orders_path %>
                <%= tab.invoice_items 'Rechnungsübersicht', invoice_items_path %>
                <%= tab.pricelist 'Preisliste', pricelist_path %>
                <% end %>
            </div>
            <hr/>
            <div id="user_balance" class="span-20 prepend-2 append-2 append-bottom last menu" style="text-align: center;">
            Aktuelles Guthaben:
            <% if current_user.balance.to_f <= 0 %>
                <span style='color: #ff0000;'>
            <% end %>
            <span id="balance"><%= number_to_currency(current_user.balance.to_f, :locale => 'de-AT') %></span>
            <% if current_user.balance.to_f <= 0 %>
                </span>
                | Bitte aufladen, um Bestellungen vorzunehmen!
            <% end %>
            </div>
            <% end %>
            <hr/>
            <div class="span-24 last">
                <%= yield %>
            </div>
        </div>
        
        <!-- uservoice -->
        <script type="text/javascript">
        var uservoiceOptions = {
          /* required */
          key: 'symbio',
          host: 'symbio.uservoice.com', 
          forum: '26811',
          showTab: true,  
          /* optional */
          alignment: 'right',
          background_color:'#f00', 
          text_color: 'white',
          hover_color: '#06C',
          lang: 'de'
        };
        
        function _loadUserVoice() {
          var s = document.createElement('script');
          s.setAttribute('type', 'text/javascript');
          s.setAttribute('src', ("https:" == document.location.protocol ? "https://" : "http://") + "cdn.uservoice.com/javascripts/widgets/tab.js");
          document.getElementsByTagName('head')[0].appendChild(s);
        }
        _loadSuper = window.onload;
        window.onload = (typeof window.onload != 'function') ? _loadUserVoice : function() { _loadSuper(); _loadUserVoice(); };
        </script>
        <!-- /uservoice -->
                
    </body>
</html>